### ISSUE TITLE
106页 第三部分 内置组件篇 倒数第二段 "DispatcherServlet方法" 首字母有误

### ISSUE THREAD

**Issue by jacarrichan** [secbr/springboot-book#3]
Java方法首字母应该是小写

![image](https://user-images.githubusercontent.com/1576779/86524037-f48e3e00-bea7-11ea-85f4-1ec641e1a6d9.jpeg)

**Comment by secbr** [comment]
非常感谢，的确如此，Java的方法名应该首字母小写。

**Comment by secbr** [comment]
重新版本已修正，感谢斧正。
