### ISSUE TITLE
P52：代码下第一段最后半句:"会忽略掉该异常并继续执行遍历操作"似乎不对。

### ISSUE THREAD

**Issue by francis-xjl** [secbr/springboot-book#5]
P52：代码下第一段最后半句:"会忽略掉该异常并继续执行遍历操作"似乎不对。

根据前面的代码块来看，当ClassNotFoundException发生时，应该不会再执行遍历操作了，接下来就是返回null了。我感觉改成“会忽略掉该异常并继续执行”会减少误解。

**Comment by francis-xjl** [comment]
刚发现有人提了，关掉吧。

**Comment by secbr** [comment]
非常感谢给出建议！
