### ISSUE TITLE
P13

### ISSUE THREAD

**Issue by liangliangchen** [secbr/springboot-book#7]
proxyBeanMethods这部分的最后一句一般情况下都配置为fas。应该是true吧，默认配置是true，平时也不会去更改该配置项。

**Comment by secbr** [comment]
此处没错误，可以看一下其他的相关配置，基本上都是false的。比如DispatcherServletAutoConfiguration类中

`
@Configuration(proxyBeanMethods = false) // 实例化配置类
	@Conditional(DefaultDispatcherServletCondition.class) // 实例化条件：通过该类来判断
	@ConditionalOnClass(ServletRegistration.class) // 存在指定的ServletRegistration类
`
